#!/bin/bash -e

# -fverbose-asm: since GCC 7.1, gcc can annotate the asm output with which
# source lines correspond to them.
# -ffixed-$reg: since GCC (TODO, version?), gcc can be instructed to avoid
# using certain registers in the generated asm.
touch decoder
DIR="$(dirname "$(readlink -f "$0")")"
gcc -I$DIR -B$DIR/gcc-bin -fverbose-asm -ffixed-r15 -lrt -pthread -Xassembler -g "$@"
